version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

# ======= FOR COMPOSE UP AND BUILDING WITH AN EXTERNAL POSTGRESQL DATABASE =======
#    depends_on:
#      - db
#    env_file:
#      - docker/.env/django.env
#  db:
#    image: postgres:13.3
#    volumes:
#      - tcrm-volume:/var/lib/postgresql/data
#    env_file:
#      - docker/.env/postgresql.env
#    ports:
#      - "5432:5432"
#volumes:
#  tcrm-volume:
#    driver: local
