# Generated by Django 3.2.3 on 2021-06-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(default='', max_length=128, unique=True)),
                ('client_secret', models.CharField(default='', max_length=128, unique=True)),
                ('client_username', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('client_password', models.CharField(default='', max_length=128, unique=True)),
                ('environment', models.CharField(choices=[('https://test.salesforce.com', 'Sandbox'), ('https://login.salesforce.com', 'Production')], default='https://test.salesforce.com', max_length=28)),
                ('name', models.CharField(default='', max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesforceenvironment',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'name'), name='unique_user_env_name'),
        ),
    ]
