# Generated by Django 3.2.3 on 2021-07-07 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(default='', max_length=128)),
                ('client_secret', models.CharField(default='', max_length=128)),
                ('client_username', models.CharField(blank=True, default='', max_length=128)),
                ('client_password', models.CharField(default='', max_length=128)),
                ('environment', models.CharField(choices=[('https://test.salesforce.com', 'Sandbox'), ('https://login.salesforce.com', 'Production')], default='https://test.salesforce.com', max_length=28)),
                ('name', models.CharField(default='', max_length=128)),
                ('instance_url', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('oauth_flow_stage', models.IntegerField(blank=True, default=0, null=True)),
                ('oauth_authorization_code', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('oauth_access_token', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('oauth_access_token_created_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesforceenvironment',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'name'), name='unique_user_env_name'),
        ),
    ]
