# Generated by Django 3.2.3 on 2021-07-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_filemodel_user_specific_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='user_specific_folder',
        ),
    ]
