# Generated by Django 3.2.3 on 2021-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_salesforceenvironment_unique_user_env_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_secret',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='salesforceenvironment',
            constraint=models.UniqueConstraint(fields=('user', 'environment', 'name'), name='unique_user_env_name'),
        ),
    ]
