# Generated by Django 3.2.3 on 2021-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210603_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceenvironment',
            name='oauth_flow_stage',
            field=models.CharField(default='', max_length=27),
        ),
    ]
