# Generated by Django 3.2.3 on 2021-07-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_dataflowcomparefilesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='main.filemodel'),
        ),
    ]
