# Generated by Django 3.2.3 on 2021-06-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_salesforceenvironment_oauth_flow_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceenvironment',
            name='oauth_access_token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='salesforceenvironment',
            name='oauth_authorization_code',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_flow_stage',
            field=models.IntegerField(default=0),
        ),
    ]
