# Generated by Django 3.2.3 on 2021-06-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210615_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_access_token',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_authorization_code',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_flow_stage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
