# Generated by Django 3.2.3 on 2021-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_notifications_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(
                choices=[('warning', 'warning'), ('success', 'success'), ('danger', 'danger'), ('info', 'info'),
                         ('primary', 'primary')], default='info', max_length=10),
        ),
    ]
