# Generated by Django 3.2.3 on 2021-08-06 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_notifications_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataflowDeprecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('salesforce_org', models.CharField(max_length=1024)),
                ('case_url', models.CharField(blank=True, default='#', max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeprecationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1024)),
                ('original_dataflow', main.modelfields.CompressedJSONField()),
                ('deprecated_dataflow', main.modelfields.CompressedJSONField()),
                ('meta', main.modelfields.CompressedJSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deprecation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataflowdeprecation')),
            ],
        ),
    ]
