# Generated by Django 3.2.3 on 2021-08-04 15:34

from django.db import migrations

import main.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_dataflowdeprecation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflowdeprecation',
            name='meta',
            field=main.modelfields.CompressedJSONField(default={}),
            preserve_default=False,
        ),
    ]
