# Generated by Django 3.2.3 on 2021-08-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_notifications_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadNotifications',
            fields=[
                ('notifications_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.notifications')),
                ('zipfile_path', models.CharField(max_length=2048)),
                ('envname', models.CharField(max_length=128)),
            ],
            bases=('main.notifications',),
        ),
    ]
