# Generated by Django 3.2.3 on 2021-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_uploadnotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataflowdeprecation',
            name='fields',
            field=models.TextField(default='<< sfdc obj fields api'),
        ),
        migrations.AddField(
            model_name='dataflowdeprecation',
            name='sobjects',
            field=models.TextField(default='<< sfdc objs api >>'),
        ),
    ]
