# Generated by Django 3.2.3 on 2021-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210831_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='deprecationdetails',
            name='message',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='deprecationdetails',
            name='status',
            field=models.IntegerField(choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'danger')], default=2),
        ),
    ]
