# Generated by Django 3.2.3 on 2021-09-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210901_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprecationdetails',
            name='status',
            field=models.IntegerField(choices=[(0, 'no-deprecation'), (1, 'success'), (2, 'info'), (3, 'warning'), (4, 'danger')], default=0),
        ),
    ]
