# Generated by Django 3.2.3 on 2021-09-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_deprecationdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String')], default='str', max_length=4),
        ),
    ]
