# Generated by Django 3.2.3 on 2021-09-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_auto_20210903_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='New Job Created', max_length=4096)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('started', 'Started'), ('progress', 'In Progress'), ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')], default='created', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='New Job Created', max_length=4096)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('started', 'Started'), ('progress', 'In Progress'), ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')], default='created', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
    ]
