# Generated by Django 3.2.3 on 2021-09-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_job_jobstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In Progress'), ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobstage',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In Progress'), ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')], default='created', max_length=10),
        ),
    ]
