# Generated by Django 3.2.3 on 2021-09-14 19:29

from django.db import migrations, models
import jsoneditor.fields.django_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('special_permission_upload_dataflows', 'Can upload dataflows')],
                'managed': False,
                'default_permissions': [],
            },
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=jsoneditor.fields.django_jsonfield.JSONField(default=dict),
        ),
    ]
