# Generated by Django 3.2.3 on 2021-09-15 19:12

from django.db import migrations
import main.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210914_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='deprecationdetails',
            name='removed_fields',
            field=main.modelfields.CompressedJSONField(blank=True, null=True),
        ),
    ]
