# Generated by Django 3.2.7 on 2021-09-22 18:11

from django.db import migrations

import main.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_deprecationdetails_removed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deprecationdetails',
            name='registers',
            field=main.modelfields.CompressedJSONField(blank=True, null=True),
        ),
    ]
