# Generated by Django 3.2.7 on 2021-10-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_deprecationdetails_registers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialpermissions',
            options={'default_permissions': [], 'managed': False, 'permissions': [('special_permission_upload_dataflows', 'Can upload dataflows'), ('special_permission_delete_all_deprecation', 'Can delete all deprecations at once')]},
        ),
    ]
