# Generated by Django 3.2.7 on 2022-07-15 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0026_dataflowuploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceenvironment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
