# Generated by Django 3.2.7 on 2022-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0027_salesforceenvironment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='environment',
            field=models.CharField(default='https://test.salesforce.com', max_length=128),
        ),
    ]
