# Generated by Django 3.2.7 on 2022-10-11 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validators.common_validators


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0028_alter_salesforceenvironment_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataflowdeprecation',
            name='case_url',
            field=models.CharField(blank=True, default='#', max_length=1024, null=True,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='dataflowdeprecation',
            name='name',
            field=models.CharField(max_length=1024,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='dataflowdeprecation',
            name='salesforce_org',
            field=models.CharField(max_length=1024,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='dataflowuploadhistory',
            name='dataflow_name',
            field=models.CharField(max_length=128, validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='dataflowuploadhistory',
            name='salesforce_env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='main.salesforceenvironment',
                                    validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='deprecationdetails',
            name='file_name',
            field=models.CharField(max_length=1024,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='deprecationdetails',
            name='message',
            field=models.CharField(blank=True, max_length=4096, null=True,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='job',
            name='message',
            field=models.CharField(default='New Job Created', max_length=4096,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In Progress'),
                                            ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')],
                                   default='created', max_length=10,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='jobstage',
            name='message',
            field=models.CharField(default='New Job Created', max_length=4096,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='jobstage',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In Progress'),
                                            ('failed', 'Failed'), ('success', 'Succeeded'), ('warning', 'Warning')],
                                   default='created', max_length=10,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.CharField(default='#', max_length=1024,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=4096,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(
                choices=[('warning', 'warning'), ('success', 'success'), ('danger', 'danger'), ('info', 'info'),
                         ('primary', 'primary')], default='info', max_length=10,
                validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.CharField(max_length=128, validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(max_length=128, validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=1024,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_key',
            field=models.CharField(default='', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator,
                                               django.core.validators.RegexValidator('^[a-zA-Z0-9]+$',
                                                                                     message='Only numbers and letters are valid')]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_password',
            field=models.CharField(default='', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator,
                                               django.core.validators.RegexValidator('^[a-zA-Z0-9]+$',
                                                                                     message='Only numbers and letters are valid')]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_secret',
            field=models.CharField(default='', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator,
                                               django.core.validators.RegexValidator('^[a-zA-Z0-9]+$',
                                                                                     message='Only numbers and letters are valid')]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='client_username',
            field=models.CharField(blank=True, default='', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='environment',
            field=models.CharField(default='https://test.salesforce.com', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='instance_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='name',
            field=models.CharField(default='', max_length=128,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_access_token',
            field=models.CharField(blank=True, default='', max_length=256, null=True,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='salesforceenvironment',
            name='oauth_authorization_code',
            field=models.CharField(blank=True, default='', max_length=256, null=True,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='uploadnotifications',
            name='envname',
            field=models.CharField(max_length=128, validators=[main.validators.common_validators.xss_absent_validator]),
        ),
        migrations.AlterField(
            model_name='uploadnotifications',
            name='zipfile_path',
            field=models.CharField(max_length=2048,
                                   validators=[main.validators.common_validators.xss_absent_validator]),
        ),
    ]
